change command names to prefix hc-, and updates all .json files with p…
holochain/holonix-archive pull request #151
Opened 2020-04-01 00:16 UTC by philipbeadle

…roject name

2020-04-01 00:39 UTC, robbiecarlton requested changes
@philipbeadle - just one small change

2020-04-01 00:39 UTC, robbiecarlton commented on happs/create/default.nix
> +  name = "hc-happ-create";
the ticket says `hc-create-happ`
I slightly prefer that, but also see the utility in using `happ` as a prefix

2020-04-01 00:39 UTC, robbiecarlton commented on happs/create/default.nix
> +    cd ..
👍

2020-04-01 01:02 UTC, philipbeadle commented on happs/create/default.nix
> +  name = "hc-happ-create";
again it how david wants it so its consistent with the rest of the commands and follows the folder structure in holonix.

2020-04-08 06:33 UTC, thedavidmeister commented on happs/create/default.nix
> +  name = "hc-happ-create";
yeah it is chaos if you name things different to the folders

2020-04-08 06:34 UTC, thedavidmeister approved these changes

2020-04-08 06:36 UTC, merged