2020 04 09/rad phase2
holochain/holonix-archive pull request #156
Opened 2020-05-13 16:43 UTC by JettTech

St## hc-happ-scaffold: A command to generate a complete and personalized Holochain Happ
> This will generate the full UI and DNA codebase as well as the conductor interface.

## 1 - Get Holonix and enter the development environment
Holonix is a full Holochain development environment built with the [Nix package manager](https://nixos.org/nix/). 
This repo comes shipped with nix-shell already baked in.  All you need to do, is enter the provided environment, by running:
```
$ nix-shell
```
## 2 - Run the hc-happ-scaffold command
From within the `nix-shell` environment, first create a directory for all your Holochain projects (if you haven't already). You can create it wherever you like; here's a recommended setup:

```
$ cd ~
$ mkdir Holochain
$ cd Holochain
```

Then run this command:

```
$ hc-happ-scaffold <PATH_TO_JSON_TYPE_SPEC> <HAPP_PROJECT_NAME>
```

This will create a new directory for your project, download all the dependencies and development tools, and create the hApp source code.

## 3 - Start your new happ!

Once it's complete, go into the new project directory and run this command:

```
$ npm run start
```

2020-05-19 20:13 UTC, robbiecarlton commented
@JettTech this will need a rewrite with the changes we made to the structure of the rad tools

2020-05-29 07:11 UTC, JettTech commented
@robbiecarlton @joel - this is ready for your review again, as all the structural updates to RAD Tools Phase 2 is complete - at least for take 1. ;+1:

2020-05-29 20:16 UTC, robbiecarlton submitted a review, later dismissed

2020-05-29 20:16 UTC, robbiecarlton commented on happs/scaffold/default.nix
> +    sed -i "s/RAD-Tools-Phase-2/"''${2:-"My-New-App"}"/g" package.json
`RAD-Tools-Phase-2` should be all lowercase now

2020-05-29 20:17 UTC, robbiecarlton commented on happs/scaffold/default.nix
> +    sed -i "s/RAD-Tools-Phase-2/"''${2:-"My-New-App"}"/g" package.json
actually, let's have this string be something more clearly a template, like `<HAPP-NAME>`

2020-05-31 17:01 UTC, JettTech commented on happs/scaffold/default.nix
> +    sed -i "s/RAD-Tools-Phase-2/"''${2:-"My-New-App"}"/g" package.json
Done.  - FYI: This is a change in the RAD tool repo itself, so the change won't be reflected here.

2020-06-03 08:39 UTC, thedavidmeister commented
@JettTech can you point me at a json spec file i can use for testing?

2020-06-03 16:41 UTC, JettTech commented
@thedavidmeister @joel - here is the link to a type-spec.json reference for testing:
https://gist.github.com/JettTech/a27fdad85f2b8f69182f5318d5b14e19

2020-06-03 19:11 UTC, zo-el approved these changes

2020-06-04 14:15 UTC, thedavidmeister requested changes

2020-06-04 14:15 UTC, thedavidmeister commented on happs/scaffold/default.nix
> +    [[ $(mimetype -b "''${1}") != "application/json" ]] && { echo "Command Usage Error: ARG 1 - JSON FILE TYPE REQUIRED"; exit 1; }
can't assume `mimetype` exists, can we add it to the build inputs?

2020-06-04 14:15 UTC, thedavidmeister commented on happs/scaffold/default.nix
> +    npm i
should we be using yarn?

2020-06-04 14:15 UTC, thedavidmeister commented on happs/scaffold/default.nix
> +    ''${1?"Command Usage Error: ARG 1 - PATH TO SCHEMA REQUIRED"}
@JettTech i was hoping we could point at URLs as well as paths for the whole process, here's a one liner i tried:

```
nix-shell https://github.com/holochain/holonix/archive/2020-04-09/rad-phase2.tar.gz --run 'hc-happ-scaffold https://tinyurl.com/ybgdhtwa $TMP/bar && cd $TMP/bar && npm run start'
```

the tiny url points to the gist you linked above

doesn't work it seems to need a local path

2020-06-04 14:16 UTC, thedavidmeister commented
@JettTech also can we get some tests written for this?

2020-06-04 18:03 UTC, JettTech commented on happs/scaffold/default.nix
> +    npm i
As a team, we had decided to use npm.  Do you have a strong opinion in favor for yarn?  Open to hearing your thoughts.

2020-06-04 18:08 UTC, JettTech commented on happs/scaffold/default.nix
> +    ''${1?"Command Usage Error: ARG 1 - PATH TO SCHEMA REQUIRED"}
This is correct, the expected behavior is for it to build based on a reference to a local path. Generally, the goal was to keep things as simple as possible for the first version, but I do agree that it be best if the path could be a url or file reference.  I'll look into this.

2020-06-09 17:05 UTC, thedavidmeister approved these changes
i approve once the tests pass :)

2020-06-12 01:33 UTC, zo-el approved these changes

2020-06-12 01:47 UTC, merged